modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="LGPLv3"

[[mods]] #mandatory
modId="hyle" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Hyle" #mandatory
logoFile="logo.png" #optional

credits="Jared & Darkhax for Multiloader" #optional
authors="lilypuree" #optional
description='''
A versatile underground stone replacer library
'''

[[dependencies.hyle]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.hyle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.20.2)"
    ordering="NONE"
    side="BOTH"
